### PR TITLE
Changed the How to Play section in the readme

### LINKED ISSUE #8: Change the How to Play section in the readme
### Currently, the How to Play section in the readme looks as follows:

1. Clone the repository or download the zip file.
2. Install the necessary dependencies using npm install.
3. Run the game using npm run dev.
4. Choose the Single Player or Multiplayer mode and play the game.

These are the steps for contributing to the Game and it is for the developers, we have to change these steps according to the non-technical person who just wants to play the game and doesn't want to clone the repository, etc.

### The steps for the How to Play section should be as follows:

1. Go to [rockout.vercel.app](https://rockout.vercel.app)
2. Choose between singlePlayer and multiPlayer modes (Create a Room & Join a Room)
3. If you select singlePlayer mode, enter the number of rounds you want to play
4. If you select Create a Room, enter your name and the total number of rounds you want to play. If you select Join a Room, enter the roomId and your name.
5. Start playing the game and enjoy!

### PR DESCRIPTION
**Pull request by saurabh190802**
Updated the how to play section. Now there is two separate how to play instructions for both developers and end users.
fixed #8

### CODE REVIEW

**Review by pushkaraj2007 — COMMENTED** [review]
Why did you add so many commits?

**Review by pushkaraj2007 — CHANGES_REQUESTED** [review]
Can you please remove the 'How to Play(For Developers)' section?

And only keep the section name as 'How to Play' without any extra information.

**Comment by saurabh190802** [comment]
> Can you please remove the 'How to Play(For Developers)' section?
> 
> And only keep the section name as 'How to Play' without any extra information.

ok

**Comment by pushkaraj2007** [comment]
@saurabh190802 

Looks good now!

**Comment by saurabh190802** [comment]
> Looks good! 🔥
> 
> Thank you for contributing. Don't forget to leave a star if you liked the project! ⭐
> 
> If you have any queries related to this project or want to connect with me, feel free to DM me on Twitter. My Twitter username is [@pushkaraj2007](https://twitter.com/pushkaraj2007) 🤝

ya sure

**Pull request merged**
