### PR TITLE
[fixed] Title of room page

### PR DESCRIPTION
**Pull request by saurabh190802**
#6 fixed kindly check @pushkaraj2007

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
This PR includes #11

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
@pushkaraj2007 - any update?

**Comment by pushkaraj2007** [comment]
@KendallDoesCoding 

I'm not getting enough time to review the entire code. Have you looked through all the code changes?

And do they look good to you?

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding
> 
> I'm not getting enough time to review the entire code. Have you looked through all the code changes?
> 
> And do they look good to you?

I mean, the issue has been fixed, but idk about the code.

**Comment by saurabh190802** [comment]
@KendallDoesCoding @pushkaraj2007 
`<ErrorPage title="This room does not exist anymore" statusCode={404} />`
this is dominating as there is no title for the outermostdiv so i have added the below to outermostdiv.
```
<Head>
          <title>Room: {slug}</title>
</Head>
```

**Pull request closed without merging**
